### ISSUE TITLE
Return numexpr expression for given container

### ISSUE THREAD

**Issue by marinang** [scikit-hep/formulate#20]
Would it be possible to return the numexpr for instance for a dict of numpy arrays / a numpy record array?

For instance like this

`arrays = {"X_PX": array(....), "X_PY": array(....), "X_PZ": array(....)}`
`momentum = formulate.from_root('TMath::Sqrt(X_PX**2 + X_PY**2 + X_PZ**2)')` 
`momentum.to_numexpr(arrays)`
which returns
`'sqrt(((arrays["X_PX"] ** 2) + (arrays["X_PY"] ** 2) + (arrays["X_PZ"] ** 2)))'`

Could it be evaluated by numexpr then ?

Matt

**Comment by marinang** [comment]
Actually I just discovered one can do:

`ne.evaluate( momentum.to_numexpr(arrays) , arrays)`

**Comment by chrisburr** [comment]
Just to check, is this issue resolved and can be closed?

**Comment by marinang** [comment]
Yes it can be closed 😄
