### ISSUE TITLE
Add pypi password as secret for CD

### ISSUE THREAD

**Issue by mayou36** [scikit-hep/formulate#31]
Can we add the PyPI Password as a secret? This is needed for the CD and 0.1.0. Or should this even be a org secret?

@henryiii @eduardo-rodrigues?

**Comment by henryiii** [comment]
We have a token for each project. I can do it, just a sec.

**Comment by henryiii** [comment]
Done!

It safer to have a token for each project, vs. a single one and and org secret, I think.
