### ISSUE TITLE
Release tagging

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/formulate#32]
Tags should have `vX.Y.Z` format, not `X.Y.Z` (only 0.1.0 is this way - GitHub's own UI gives this recommendation), and a GitHub release should always be made when tagging, so it shows up in the UI. @mayou36, perhaps you can can fix?

**Comment by mayou36** [comment]
Indeed, that was an oversight. I'll do a v0.1.1 release to have it proper, okay?

**Comment by henryiii** [comment]
That's fine, though you could also tag v0.1.0 to match 0.1.0.

**Comment by mayou36** [comment]
Doesn't that may interfere with PyPI? The upload should fail surely

**Comment by mayou36** [comment]
Released, https://github.com/scikit-hep/formulate/releases/tag/v0.1.1, thanks for spotting this!
