### ISSUE TITLE
Revert the LICENSE holder to what it was

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/formulate#50]
Hi @aryan26roy, can you please revert the holder name to what it was? (You should not even change such a thing  without explicit OK from everyone involved since a copyright ;-).)

**Comment by eduardo-rodrigues** [comment]
And you should then revert accordingly minor bits from https://github.com/scikit-hep/formulate/commit/032bad5c1709766a8a71412ecbff799863c06ef0.

**Comment by aryan26roy** [comment]
@eduardo-rodrigues Sorry about that. It was autogenerated by cookiecutter. Should I make a new release after I have reverted the holder name?

**Comment by eduardo-rodrigues** [comment]
I see you made a release candidate for 1.0. If you fix for the actual release I reckon that is OK.
